server:
  port: 9999
spring:
  application:
    name: enviroment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.34.35:3306/environment?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20020217
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis-plus:
  global-config:
    db-config:
      # update时 跳过对象里null值的属性（null表示不更新）
      update-strategy: not_null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: kob_token
  # token有效期，单位s 默认7天, -1代表永不过期
  timeout: 604800 # 60s*60m*24h*7d
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 36000 # 60*60 连续一小时无操作，下次操作时记录登录信息
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 禁用cookie
  is-read-cookie: false
  # 关闭自动续签, 手动实现自动续签
  auto-renew: false
  is-print: false


#日志
logging:
  file:
    path: ./log/
  level:
    com.peels: debug

aliyun:
  oss:
    avatar:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tBkx5yHPJtJc2maaoj7
      keysecret: ah70DssneljMByNzla1oo0Gs2AqldB
      bucketname: learning-glxy-images

feign:
  client:
    config:
      default:
        loggerLevel: FULL

#  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
openai:
  key:  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZW51bSI6IjE5NTU5MjAwMTA2IiwiaWQiOjkxOTEsInN1YiI6IkF1dGhlbnRpY2F0aW9uIiwiZXhwIjoxNjg3MjMzODY4LCJqdGkiOiIwNTNlM2EwY2QwMTY0OTcwOTg0ZWUzYTJmODFkYjU2MiJ9.qMjHASSq-KMpU6YDYfnV8d-qesFXwUh9e7opr3PDkOQ
  name: Peelsannaw
  timeout: 1000000
  model: gpt-3.5-turbo